name: GoCI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .go-version
      - .golangci.yml
      - '**/*.go'
      - go.sum
      - main.go

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  golangci-lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: go env
      run: |
        echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV
    - run: cd tools && go install github.com/golangci/golangci-lint/cmd/golangci-lint
    - run: golangci-lint run ./...
